version: "3"

networks:
  proxy-net:
    external: true

volumes:
  docmost:
  db_data:
  redis_data:

services:
  docmost:
    image: docmost/docmost:latest
    networks:
      - proxy-net
      - default
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    environment:
      APP_URL: https://docmost.example.com
      APP_SECRET: random_long_secret
      DATABASE_URL: postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public
      REDIS_URL: redis://redis:6379

      # Only if you need multi user:
      # MAIL_DRIVER: smtp
      # SMTP_HOST: smtp.gmail.com
      # SMTP_PORT: 465
      # SMTP_USERNAME: YOUR_EMAIL
      # SMTP_PASSWORD: app-password
      # MAIL_FROM_ADDRESS: YOUR_EMAIL
      # MAIL_FROM_NAME: Docmost
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
